### ISSUE TITLE
go fmt

### ISSUE THREAD

**Issue by mcuadros** [djosephsen/slacker#2]
I wish to contribute, because we are using slacker at our company. But I cannot because your code is not formatted against `go fmt`. A small [sneak peak](https://github.com/djosephsen/slacker/blob/b2e9dbc4517684a43d8b169fd8eb4339cca9d444/slackerlib/broker.go#L104)

Can you pass go fmt? Thanks
BTW excellent job!

**Comment by djosephsen** [comment]
Hi!  

Yes I've been meaning to fmt this for some time and I'll do that and get back to ya. 

Having said that though;  using slacker in anger has convinced me that this was never the right way to do  a chatops bot in GO.  Over the last several months I've been rewriting and I've wound up with something much better that I'm sure I'll be sticking with for my own use, which means I'll most likely be abandoning slacker altogether. 

So the bad news is that I'm probably abandoning this project, but the good news is that if you like slacker, you'll love [lazlo](http://github.com/djosephsen/lazlo).  So ESPECIALLY if you want to contribute, come check out [lazlo](http://github.com/djosephsen/lazlo), I think you'll find it's soooo much nicer to write automation in.  (it also needs some go fmt love heh)

**Comment by mcuadros** [comment]
lazlo is stable? I will take a look ASAP. BTW I suggest you include a note in the read to forward the users to lazlo :D

Thanks! Awesome job!
